### ISSUE TITLE
whers is the code to product the activation map ?

### ISSUE THREAD

**Issue by JXQI** [zzdyyy/Patho-GAN#1]

**Comment by zzdyyy** [comment]
use tfpipe_dump_activation.py:

python tfpipe_dump_activation.py data/IDRiD/test_512/*.jpg --dump_to IDRiD_test --visualize

and you can find the activation maps in Visualization/IDRiD_test/

you can turn down the scale "0.1" in line 59 "projections = (projections - p_mean) / 0.1" for better visulization
